GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "id": 5,
    "name": "jarnooo",
    "number": "123"
}

###
DELETE http://localhost:3001/api/persons/1 HTTP/1.1